name: scidart_plot
description: SciDart Plot is a data visualization library compatible with SciDart. This library is part of SciDart project. The main goal is Generate and save plots in SVG format.
version: 0.0.1-dev.2
homepage: https://github.com/scidart/scidart_plot

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: ^1.1.7
  scidart: ^0.0.1-dev.9

dev_dependencies:
  pedantic: ^1.9.2
  test: ^1.15.7
  scidart_io: ^0.0.1-dev.6