name: scidart_plot
description: SciDart Plot is a data visualization library compatible with SciDart. This library is part of SciDart project. The main goal is Generate and save plots in SVG format.
version: 0.0.1-dev.1
homepage: https://github.com/scidart/scidart_plot
author: Ângelo Polotto <angelopolotto@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
#  path: ^1.6.4
  scidart: ^0.0.1-dev.5
  scidart_io: ^0.0.1-dev.3
  color: ^2.1.1

dev_dependencies:
  pedantic: ^1.7.0
  test: ^1.6.0